name: Build_TVBox

on:
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 自动清理冲突文件
        # 这一步非常关键，删除作者本地的路径配置
        run: |
          rm -f local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: 赋予执行权限
        run: chmod +x gradlew

      - name: 开始编译 APK
        # 如果依然报错，我们加上 --stacktrace 查看具体原因
        run: ./gradlew assembleDebug -x lint -x test --stacktrace

      - name: 上传 APK 产物
        uses: actions/upload-artifact@v4
        with:
          name: TVBox_Build
          path: app/build/outputs/apk/debug/*.apk
